kits/cpp/src/agent.cpp

@StoneT2000 I noticed that the cpp agent would cause an error in the runner when it did not submit any actions. Turns out lux expects at least an empty object, so I fixed the agent.

Avoid returning None when no action is submitted in act

---

README.md
kits/python/README.md

The link to the local notebook was missing part of the path. 
Capitalized Python and NumPy as they were used as the name of the package.

Fixed a broken link + capitalized Python/NumPy

---

luxai2022/map/weather.py

Fixed a bug in the calculation of 'requested_times' in the 'generate_weather_schedule' function.
In the original program, the calculation method for 'requested_times' was incorrect and could cause weather overwriting.

fix weather schedule generation logic

---

luxai_runner/process.py

All stderr from agents is currently printed out with an extra newline after every line when running using the CLI. This PR removes that extra newline, which makes multi-line log messages (like stack traces) more readable in my opinion.
Before:
After:

Fix double newline on agent stderr

---

luxai_runner/episode.py
luxai_runner/process.py

This fix references [this issue](https://github.com/Lux-AI-Challenge/Lux-Design-2022/issues/80). I don't fully understand what's going on to cause the issue, but it seems that without properly waiting for subprocesses to terminate, we get errors from pending I/O operations. I went ahead and added a cleanup method to be run at the end of execution for an episode, which seems to resolve the issue on windows. 
With better understanding of the bug, someone might be able to make a cleaner solution this what I have here.

Fix ValueError: I/O operation on closed pipe error on Windows 10

---

README.md
luxai_runner/utils.py

Fixes #104 
Now:
* all np.integers are converted to int
* tuples are handled like lists
* added np.float conversiont to float
I also renamed state to obj, since reflects better what is happening as it is a nested object conversion.

#104: fix for to_json for numpy integers and tuples

---

kits/cpp/src/lux/unit.hpp

Action queues for units weren't getting populated because it was missing from the json serialization.

Add unit action_queue to C++ json serialization

---

luxai_runner/process.py

If you try to run a java program using the luxai2022 command, we will fail with the following error:
```
Error: Could not find or load main class $CLASS_NAME.java
```
The problem is we are trying to execute the following command:
```
java $CLASS_NAME.java
```
Which is not the proper compilation/execution pattern for java. Instead, after you run `javac $CLASS_NAME.java`, you are expected to run your newly compiled code with the following command: `java $CLASS_NAME`, where we neglect the file extension. I've gone ahead and done this manually before we create the subprocess and it seems to work in my most basic of tests.

Fix inability to run Java programs with Luxai2022 runner

---

kits/cpp/src/lux/observation.cpp

This is necessary to account for dying factories.

Reset factory_occupancy map before update

---

kits/cpp/Dockerfile

When running `./create_submission.sh` it's possible that it will fail due to CMake version being < `3.12` which is required.
By updating the base image we ensuere that CMake `3.16` is used. Successfully tested locally.

[Update] bump ubuntu version to get higher cmake version

---

kits/cpp/src/lux/action.hpp

Was missed when updating the kit to 1.1.0

[cpp] Fix repeat field type

---

kits/cpp/src/lux/action.hpp

A poor `bool` was forgotten in the v1.1.0 refactor. It's evolving! `bool` is now `int64_t`!
Why: with `bool` any repeat is converted to `0/1`.

[Fix] repeat type in action: bool to int

---

kits/cpp/src/lux/board.cpp

The `valid_spawns_mask` attribute is only available in the first k turns, so we need to check if it's there to avoid an exception. Somehow making turn information available here would be too cumbersome.

Update spawn mask when available

---

kits/cpp/src/lux/factory.cpp

This was changed in the python kit a few days ago. @StoneT2000 feel free to ping me when you change aspects of the python kit, so I can adjust this kit at the same time / only with a slight delay.

Fix factory water cost calculation in C++ kit

---

luxai2022/env.py

Fix a severe bug in transfer action, which allow the robot to transfer any amount of resources to a factory, even if it does not have enough resources. Because we do not check transfer amount is valid or not, we cannot trust the amount given by users now. Before adding it to a factory, we must take a minimum between the transfer amount and the robot cargo stock.

Fix a severe bug in transfer action

---

luxai2022/env.py

Fix a bug in env.step that may lead to crashing. When updating the action queue, all exceptions will be caught and printed. However,  `e.with_traceback()` takes one argument, and nothing is given. This will lead to the whole game crashing. 
The most common case to trigger the crash is when a player provides actions for a non-existing robot or a robot he/she does not own.

Fix a bug in env.step that may lead to crash.

---

kits/python/lux/kit.py

In the py-kit factory_occupancy_map uses the team_id instead of the factory id. Therefore it always shows factory_0 for player_0 no matter which factory_id it actually is. This causes crashes when factory_0/1 die.

Fix bug: factory_occupancy_map using the same id for all factories 

---

luxai2022/factory.py

When searching for watering tiles of the current factory, if a neighbor is an occupancy tile (not strain tile) of another factory, then the current pos is also not growable according to the rule because the current pos is expandable for both the current factory and another factory.

Fix a bug in water info

---

luxai2022/env.py

For factories with insufficient power/resources, we should skip them and continue to handle other factories' build action, not directly return from the function.

Fix a bug in factory build action.

---

luxai2022/env.py

There is a typo, which leads to a bug when the amount of metal assigned to a factory exceeds the player's budget.

fix a bug in factory placement step

---

kits/cpp/src/agent.cpp
kits/cpp/src/lux/observation.cpp
kits/cpp/src/lux/unit.cpp

Adjusts cpp kit to new changes.

Store strain id in occupancy map instead of team id

---

luxai2022/env.py

Before, the transfer result relies on the unit_id because the transfer is executed from units with small id to ones with big id. For example, consider three light robots, A, B, and C, with a cargo space of 100. Initially, they both have 80 water. Now, A wants to transfer 80 water to B, and B wants to transfer 80 water to C.
```
A   B   C
initial:  80  80  80
action: A -80-> B -80-> C
```
If `A.unit_id` < `B.unit_id`, then A transfers first. After transfer, B has 100 water because of the cargo space limit. Then B transfers 80 water to C and has only 20 left.
If `B.unit_id` < `A.unit_id`, then B transfer first. After transfer, B has 0 water. Then A transfer 80 water to B, and B finally has 80.
```
A   B   C
final:    0  20 100,  if A.unit_id < B.unit_id
0  80 100,  if B.unit_id < A.unit_id …
```

Fix: make transfer action irrelevant to unit_id.

---

kits/cpp/compile.sh

The current compilation helper only checked that cmake is installed. This adds checks for the other required tools due to #139 
The check for a suitable cpp compiler is done by cmake.

Add dependency checks for cpp kit

---

luxai_s2/luxai_s2/unit.py

The change log of v2.0.0 says, "actions in an action queue can specify both the number of times to repeat it directly, as well as whether to put it back to the end of the action queue once exhausted." However, it is not implemented in `unit.repeat_action`. This commit implements the such feature.

fix: actions correctly repeat now

---

luxai_s2/luxai_s2/env.py

When two heavy enter the same tile, the surviving one was not added to the new unit's map. This bug leads to crashing in the next step.

fix a bug in _handle_movement_actions

---

lux-eye-s2/src/pages/home/HomePage.tsx
lux-eye-s2/src/pages/home/LoadFromFile.tsx
lux-eye-s2/src/pages/open/OpenPage.tsx
lux-eye-s2/src/store.ts
luxai_s2/luxai_runner/cli.py
luxai_s2/luxai_runner/episode.py

- Added support for `--replay.save_format html` to the CLI. Generated HTML replays show the replay in the visualizer when opened in the browser.
- Changed the default value of `--replay.save_format` to be the extension passed to `--output`, so when running `luxai-s2 --output replay.html` it defaults to HTML format and when running `luxai-s2 --output replay.json` it defaults to JSON format. When there is no extension or it is invalid then JSON format is used.
- Added support for loading HTML replays to the "Load from file" functionality in the visualizer.

Add support for HTML replays

---

lux-eye-s2/src/episode/luxai-s2.ts
lux-eye-s2/src/episode/model.ts
lux-eye-s2/src/pages/visualizer/RobotDetail.tsx

Updated the visualizer so that it renders the label on repeating actions as `n/repeat` rather than only displaying the repeat value for 2.1.0+ episodes.

Update visualizer for n/repeat changes in 2.1.0

---

lux-eye-s2/src/episode/luxai-s2.ts
lux-eye-s2/src/episode/model.ts
lux-eye-s2/src/pages/visualizer/TeamCard.tsx

This PR makes the visualizer able to visualize episodes where the actions object of a player is `null` for one or more steps. This appears to happen when a team's submission crashes during the episode. At the moment the visualizer shows an error when trying to open these episodes, after this PR it will show "Winner by opponent error" on the winning team and display an error message on the step it happens. An example episode is 46255931:

Support visualizing episodes with null actions

---

luxai_s2/luxai_runner/process.py

If the subprocess is terminated on it's own before the tournament task gets a chance to cleanup itself, the cleanup function errors and causes a premature crash on Windows. Here's an example of what that looks like:
```
Traceback (most recent call last):
File "/home/amon/.local/bin/luxai-s2", line 8, in <module>
sys.exit(main())
File "/home/amon/.local/lib/python3.10/site-packages/luxai_runner/cli.py", line 154, in main
asyncio.run(tourney.run())
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
return future.result()
File "/home/amon/.local/lib/python3.10/site-packages/luxai_runner/tournament/tournament.py", line 120, in run
await asyncio.gather(*coros, …
```

Fix tournament mode errors for Windows/Java combination

---

lux-eye-s2/src/pages/visualizer/Board.tsx
lux-eye-s2/src/pages/visualizer/UnitCard.tsx
lux-eye-s2/src/pages/visualizer/UnitList.tsx
lux-eye-s2/src/store.ts

Requested on Discord: https://discord.com/channels/753650408806809672/800945957956485130/1073323591724179619
When you hover over a factory/robot in the visualizer the detail card of that unit is automatically scrolled into view in the factory/robot list of the team it belongs to. The current behavior is to only scroll this list if the card is not already in view, and to scroll it to the top of the list of visible items if it's above the currently visible items and to the bottom if it's below the currently visible items. This PR changes that so that it always scrolls the list to move the detail card to top of the list (if possible), and so that it also scrolls the card to the top if it's already in view but not at the top.

Make factory and robot lists scroll to top on hover

---

lux-eye-s2/src/episode/luxai-s2.ts
lux-eye-s2/src/episode/model.ts
lux-eye-s2/src/pages/visualizer/Board.tsx
lux-eye-s2/src/pages/visualizer/Chart.tsx
lux-eye-s2/src/pages/visualizer/TeamCard.tsx
lux-eye-s2/src/pages/visualizer/VisualizerPage.tsx

Fixes #206. At the moment, on every step the visualizer creates a strain -> team mapping describing what team owns each strain. However, the strains are stored in the factories so when one of them gets destroyed the visualizer incorrectly no longer maps that factory's strain to the team it belonged to. This PR changes that by using the strains stored in `step.teams.player_0/1.factory_strains` instead.

Fix visualizer for lichen strains of destroyed factories
